### ISSUE TITLE
Implementing basic functionality mapping

### ISSUE THREAD

**Issue by Akalanka47000** [sliit-foss/mongoose-filter-query#1]
Map the basic filter queries listed in the readme file

**Comment by zaahmed-nisum-com** [comment]
@Akalanka47000  can i work on it please. Also can you add some details please.

**Comment by Akalanka47000** [comment]
Sure Zaahmed, 

The details are included in the readme file. If I simplify a scenario further, imagine for a request with a query string specified as follows - 'http://localhost:3000/api/users?filter[first_name]=eq(John)', the requested filters should be extracted and constructed into the format which is understood by mongoDB which is :
```javascript
{
  first_name: "John"
}
```
